# Generated by Django 2.1.7 on 2019-06-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contanct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contanct',
            new_name='Contact',
        ),
    ]
